package org.example.uvi.App.Infrastructure.Http.Controller.AuthController;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.example.uvi.App.Domain.Services.AuthService.AuthService;
import org.example.uvi.App.Domain.Services.TwoFactorService.TwoFactorService;
import org.example.uvi.App.Infrastructure.Http.Dto.AuthDto.AuthResponse;
import org.example.uvi.App.Infrastructure.Http.Dto.AuthDto.RefreshTokenRequest;
import org.example.uvi.App.Infrastructure.Http.Dto.AuthDto.SendSmsRequest;
import org.example.uvi.App.Infrastructure.Http.Dto.AuthDto.TwoFactorSetupResponse;
import org.example.uvi.App.Infrastructure.Http.Dto.AuthDto.TwoFactorVerifyRequest;
import org.example.uvi.App.Infrastructure.Http.Dto.AuthDto.VerifySmsRequest;
import org.example.uvi.App.Infrastructure.Security.JwtService;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/v1/auth")
@RequiredArgsConstructor
@Tag(name = "Auth", description = "Authentication and Multi-Factor security")
public class AuthController {

    private final AuthService authService;
    private final TwoFactorService twoFactorService;
    private final JwtService jwtService;

    @PostMapping("/send-code")
    @Operation(
            summary = "Send SMS verification code",
            description = "Initiates the login flow by sending a 4-digit code to the specified phone number."
    )
    public ResponseEntity<Void> sendCode(@Valid @RequestBody SendSmsRequest request) {
        authService.sendCode(request.phoneNumber());
        return ResponseEntity.ok().build();
    }

    @PostMapping("/verify-code")
    @Operation(
            summary = "Verify SMS code and get tokens",
            description = "Validates the SMS code and returns JWT access/refresh tokens. If 2FA is enabled, returns a flag instead of tokens."
    )
    public ResponseEntity<AuthResponse> verifyCode(
            @Valid @RequestBody VerifySmsRequest request,
            HttpServletRequest httpRequest) {
        String deviceInfo = httpRequest.getHeader("User-Agent");
        return ResponseEntity.ok(authService.verifyCode(request.phoneNumber(), request.code(), deviceInfo));
    }

    @PostMapping("/refresh")
    @Operation(
            summary = "Refresh access token",
            description = "Uses a valid refresh token to obtain a new access token and a rotated refresh token."
    )
    public ResponseEntity<AuthResponse> refresh(
            @Valid @RequestBody RefreshTokenRequest request,
            HttpServletRequest httpRequest) {
        String deviceInfo = httpRequest.getHeader("User-Agent");
        return ResponseEntity.ok(authService.refreshTokens(request.refreshToken(), deviceInfo));
    }

    @PostMapping("/logout")
    @Operation(
            summary = "Logout",
            description = "Revokes all refresh tokens for the current user across all devices.",
            security = @SecurityRequirement(name = "bearerAuth")
    )
    public ResponseEntity<Void> logout(Authentication authentication) {
        Long userId = (Long) authentication.getPrincipal();
        authService.logout(userId);
        return ResponseEntity.ok().build();
    }

    @PostMapping("/2fa/setup")
    @Operation(
            summary = "Setup Google 2FA",
            description = "Generates a new TOTP secret and returns a QR code URL for apps like Google Authenticator.",
            security = @SecurityRequirement(name = "bearerAuth")
    )
    public ResponseEntity<TwoFactorSetupResponse> setup2fa(Authentication authentication) {
        Long userId = (Long) authentication.getPrincipal();
        String qrUrl = twoFactorService.setupTwoFactor(userId);
        // Извлекаем secret из URL для ручного ввода
        String secret = qrUrl.contains("secret=")
                ? qrUrl.split("secret=")[1].split("&")[0]
                : "";
        return ResponseEntity.ok(new TwoFactorSetupResponse(qrUrl, secret));
    }

    @PostMapping("/2fa/confirm")
    @Operation(
            summary = "Confirm 2FA setup",
            description = "Finalizes 2FA activation by verifying the first TOTP code generated by the user's app.",
            security = @SecurityRequirement(name = "bearerAuth")
    )
    public ResponseEntity<Void> confirm2fa(
            @Valid @RequestBody TwoFactorVerifyRequest request,
            Authentication authentication) {
        Long userId = (Long) authentication.getPrincipal();
        boolean ok = twoFactorService.confirmTwoFactor(userId, request.code());
        if (!ok) return ResponseEntity.badRequest().build();
        return ResponseEntity.ok().build();
    }

    @PostMapping("/2fa/verify")
    @Operation(
            summary = "Verify TOTP code",
            description = "Second step of login flow when 2FA is enabled. Exchange TOTP code for final JWT tokens.",
            security = @SecurityRequirement(name = "bearerAuth")
    )
    public ResponseEntity<AuthResponse> verify2fa(
            @Valid @RequestBody TwoFactorVerifyRequest request,
            Authentication authentication,
            HttpServletRequest httpRequest) {
        Long userId = (Long) authentication.getPrincipal();
        String deviceInfo = httpRequest.getHeader("User-Agent");
        return ResponseEntity.ok(authService.verifyTwoFactor(userId, request.code(), deviceInfo));
    }

    @DeleteMapping("/2fa")
    @Operation(
            summary = "Disable 2FA",
            description = "Removes the TOTP secret and disables 2FA for the current account.",
            security = @SecurityRequirement(name = "bearerAuth")
    )
    public ResponseEntity<Void> disable2fa(Authentication authentication) {
        Long userId = (Long) authentication.getPrincipal();
        twoFactorService.disableTwoFactor(userId);
        return ResponseEntity.ok().build();
    }

    @GetMapping("/csrf")
    @Operation(
            summary = "Prime CSRF cookie",
            description = "Call this endpoint before any POST/PUT/DELETE request to receive the XSRF-TOKEN cookie required for CSRF protection."
    )
    public ResponseEntity<Void> primeCsrf() {
        return ResponseEntity.ok().build();
    }
}
